### ISSUE TITLE
Request for your paper

### ISSUE THREAD

**Issue by stvsd1314** [Webbah/safe-reinforcement-learing-for-microgrid-control#1]
hello,can you share the paper?

**Comment by Webbah** [comment]
Hi Steven,

thank you for interest!
Basically there is a newer version of this repo -> https://github.com/Webbah/Safe-Reinforcement-Learning-Based-Control-in-Power-Electronic-Systems 

Since only the new version is updated anymore I would refer to that.
The paper belonging to the code is curretly in the review process and the link in the other git refering to the paper will be updated in the next weeks depending on how long the review process takes.

I hope that is ok for you.

**Comment by Webbah** [comment]
Hi Steven,

meanwhile the paper is online: https://ieeexplore.ieee.org/document/10182718
